document.addEventListener('DOMContentLoaded', () => {
    // Navbar scroll effect
    const navbar = document.querySelector('.navbar');
    
    window.addEventListener('scroll', () => {
        if (window.scrollY > 50) {
            navbar.classList.add('scrolled');
        } else {
            navbar.classList.remove('scrolled');
        }
    });

    // Mobile menu toggle
    const mobileMenuBtn = document.querySelector('.mobile-menu-btn');
    const navLinks = document.querySelector('.nav-links');

    mobileMenuBtn.addEventListener('click', () => {
        mobileMenuBtn.classList.toggle('active');
        navLinks.classList.toggle('active');
    });

    // Close mobile menu on link click
    document.querySelectorAll('.nav-links a').forEach(link => {
        link.addEventListener('click', () => {
            mobileMenuBtn.classList.remove('active');
            navLinks.classList.remove('active');
        });
    });

    // Reveal animations on scroll
    const reveals = document.querySelectorAll('.reveal');

    function reveal() {
        const windowHeight = window.innerHeight;
        const elementVisible = 150;

        reveals.forEach(revealElement => {
            const elementTop = revealElement.getBoundingClientRect().top;

            if (elementTop < windowHeight - elementVisible) {
                revealElement.classList.add('active');
            }
        });
    }

    window.addEventListener('scroll', reveal);
    reveal(); // Trigger once on load

    // Razorpay Integration
    const checkoutButtons = document.querySelectorAll('.btn-checkout');
    const API_URL = "https://v97j2s2fo3.execute-api.us-east-1.amazonaws.com";
    
    checkoutButtons.forEach(button => {
        button.addEventListener('click', async () => {
            const originalText = button.innerText;
            button.innerText = "Processing...";
            button.disabled = true;

            try {
                // 1. Create Order via Backend
                const orderResponse = await fetch(`${API_URL}/create-order`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ amount: 5000, currency: "INR" }) // 5000 paise = 50 INR
                });

                const orderData = await orderResponse.json();

                if (!orderResponse.ok) {
                    throw new Error(orderData.error || 'Failed to create order');
                }

                // 2. Open Razorpay Checkout Modal
                const options = {
                    "key": "rzp_test_TFEZVD3yQyffzr", // User provided frontend key
                    "amount": orderData.amount,
                    "currency": orderData.currency,
                    "name": "masterji.online",
                    "description": "Doorstep Tailor Booking Fee",
                    "image": "logo.png.jpeg",
                    "order_id": orderData.order_id, // Order ID generated by backend
                    "handler": async function (response) {
                        // 3. Verify Payment Signature via Backend
                        try {
                            const verifyResponse = await fetch(`${API_URL}/verify-payment`, {
                                method: 'POST',
                                headers: { 'Content-Type': 'application/json' },
                                body: JSON.stringify({
                                    razorpay_order_id: response.razorpay_order_id,
                                    razorpay_payment_id: response.razorpay_payment_id,
                                    razorpay_signature: response.razorpay_signature
                                })
                            });

                            const verifyData = await verifyResponse.json();

                            if (verifyResponse.ok && verifyData.status === 'success') {
                                alert("Booking Successful! Payment Verified. Payment ID: " + response.razorpay_payment_id);
                            } else {
                                alert("Payment Verification Failed: " + (verifyData.error || 'Tampered data'));
                            }
                        } catch (err) {
                            console.error(err);
                            alert("Error verifying payment.");
                        }
                    },
                    "notes": {
                        "address": "Doorstep Measurement Service"
                    },
                    "theme": {
                        "color": "#FFD700"
                    }
                };
                
                const rzp = new Razorpay(options);
                rzp.on('payment.failed', function (response){
                    alert("Payment Failed: " + response.error.description);
                });
                rzp.open();
                
            } catch (err) {
                console.error(err);
                alert("Error initiating checkout: " + err.message);
            } finally {
                button.innerText = originalText;
                button.disabled = false;
            }
        });
    });
});
